# Generated by Django 4.1.7 on 2023-03-25 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mieszkomotors.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_mieszkomotors_since', models.DateField(auto_created=True, auto_now=True)),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('license_plates', models.CharField(max_length=8, unique=True)),
                ('current_car_review_date', models.DateField()),
                ('car_review_renewal_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnterpriseOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('address_prefix', models.CharField(choices=[('ul.', 'ul.'), ('al.', 'al.'), ('os.', 'os.'), ('pl.', 'pl.')], default='ul.', max_length=3)),
                ('street', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('building', models.CharField(max_length=10)),
                ('apartment', models.CharField(max_length=12)),
                ('nip', models.CharField(blank=True, max_length=10, null=True)),
                ('regon', models.CharField(blank=True, max_length=10, null=True)),
                ('client_since', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('address_prefix', models.CharField(choices=[('ul.', 'ul.'), ('al.', 'al.'), ('os.', 'os.'), ('pl.', 'pl.')], default='ul.', max_length=3)),
                ('street', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('building', models.CharField(max_length=10)),
                ('apartment', models.CharField(max_length=12)),
                ('pesel', models.CharField(blank=True, max_length=10, null=True)),
                ('client_since', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('offer', models.TextField(blank=True, max_length=500, null=True)),
                ('current_insurance_date', models.DateField()),
                ('insurance_renewal_date', models.DateField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='mieszkomotors.car')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='mieszkomotors.individualowner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelfEmployedOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('address_prefix', models.CharField(choices=[('ul.', 'ul.'), ('al.', 'al.'), ('os.', 'os.'), ('pl.', 'pl.')], default='ul.', max_length=3)),
                ('street', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('building', models.CharField(max_length=10)),
                ('apartment', models.CharField(max_length=12)),
                ('nip', models.CharField(blank=True, max_length=10, null=True)),
                ('regon', models.CharField(blank=True, max_length=10, null=True)),
                ('client_since', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelfEmployedOwnerNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.selfemployedowner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelfEmployedOwnerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(upload_to=mieszkomotors.models.base.get_upload_path)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.selfemployedowner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsurancePartialPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('payment_1', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_1_status', models.CharField(choices=[('p', 'Zapłacona'), ('np', 'Niezapłacona'), ('o', 'Opóźniona')], max_length=2)),
                ('payment_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_2_status', models.CharField(choices=[('p', 'Zapłacona'), ('np', 'Niezapłacona'), ('o', 'Opóźniona')], max_length=2)),
                ('payment_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_3_status', models.CharField(choices=[('p', 'Zapłacona'), ('np', 'Niezapłacona'), ('o', 'Opóźniona')], max_length=2)),
                ('payment_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_4_status', models.CharField(choices=[('p', 'Zapłacona'), ('np', 'Niezapłacona'), ('o', 'Opóźniona')], max_length=2)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.insurance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.insurance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceAttachement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('attachement', models.FileField(upload_to=mieszkomotors.models.base.get_upload_path)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.insurance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='insurance',
            name='partial_payments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_payment', to='mieszkomotors.insurancepartialpayments'),
        ),
        migrations.CreateModel(
            name='IndividualOwnerNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.individualowner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualOwnerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(upload_to=mieszkomotors.models.base.get_upload_path)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.individualowner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnterpriseOwnerNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.enterpriseowner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnterpriseOwnerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('attachment', models.FileField(upload_to=mieszkomotors.models.base.get_upload_path)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.enterpriseowner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarSelfEmploedOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('a', 'Aktywny'), ('n', 'Nieaktywny')], max_length=3)),
                ('assign_date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.selfemployedowner')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(max_length=500)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.car')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarIndividualOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('a', 'Aktywny'), ('n', 'Nieaktywny')], max_length=3)),
                ('assign_date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.individualowner')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarEnterpriseOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('a', 'Aktywny'), ('n', 'Nieaktywny')], max_length=3)),
                ('assign_date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.enterpriseowner')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarAttachements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('attachements', models.FileField(upload_to=mieszkomotors.models.base.get_upload_path)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.car')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='car',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_insurance', to='mieszkomotors.insurance'),
        ),
    ]
