# Generated by Django 4.1.7 on 2023-03-14 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('license_plates', models.CharField(max_length=8, unique=True)),
                ('car_review_date', models.DateField()),
                ('purchase_date', models.DateField()),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('offer', models.TextField(blank=True, max_length=500, null=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('car', models.OneToOneField(default=666, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='mieszkomotors.car')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('nip_number', models.CharField(blank=True, max_length=10, null=True)),
                ('birthday', models.DateField(null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_insurance_date', models.DateField(blank=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.insurance')),
            ],
        ),
        migrations.CreateModel(
            name='CarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_review_date', models.DateField(blank=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='mieszkomotors.insurance'),
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mieszkomotors.owner'),
        ),
    ]
