# Generated by Django 4.1.7 on 2023-03-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mieszkomotors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='in_mieszkomotors_since',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='in_mieszkomotors_since',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
    ]
