# Generated by Django 4.1.7 on 2023-03-15 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mieszkomotors', '0003_car_attachements_insurance_attachements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_insurance', to='mieszkomotors.insurance'),
        ),
    ]
